import type { PortalsTrackedCompany } from "@/lib/types";

/**
 * Curated ATS boards ApplyPanda *can* query without scraping (Greenhouse, Ashby, Lever — see `detectPortalApi`).
 *
 * **Hosted ApplyPanda** lets users pick employers from this list (checkbox UI) or add extra ATS URLs;
 * stored JSON matches career-ops `portals.yml` `tracked_companies`, same mental model as `scan.mjs`.
 */
export const DEFAULT_PORTAL_CATALOG: readonly PortalsTrackedCompany[] = [
  { name: "Ada", enabled: true, careers_url: "https://job-boards.greenhouse.io/ada" },
  { name: "Airtable", enabled: true, careers_url: "https://job-boards.greenhouse.io/airtable" },
  { name: "Aleph Alpha", enabled: true, careers_url: "https://jobs.ashbyhq.com/AlephAlpha" },
  { name: "Amplemarket", enabled: true, careers_url: "https://job-boards.greenhouse.io/amplemarket" },
  { name: "Anthropic", enabled: true, careers_url: "https://job-boards.greenhouse.io/anthropic" },
  { name: "Arize", enabled: true, careers_url: "https://job-boards.greenhouse.io/arizeai" },
  { name: "Attio", enabled: true, careers_url: "https://jobs.ashbyhq.com/attio" },
  { name: "Black Forest Labs", enabled: true, careers_url: "https://job-boards.greenhouse.io/blackforestlabs" },
  { name: "Bland", enabled: true, careers_url: "https://jobs.ashbyhq.com/bland" },
  { name: "Boomi", enabled: true, careers_url: "https://job-boards.greenhouse.io/boomilp" },
  { name: "Causaly", enabled: true, careers_url: "https://jobs.ashbyhq.com/causaly" },
  { name: "Celonis", enabled: true, careers_url: "https://job-boards.greenhouse.io/celonis" },
  { name: "Clarity AI", enabled: true, careers_url: "https://jobs.lever.co/clarity-ai" },
  { name: "Clerk", enabled: true, careers_url: "https://jobs.ashbyhq.com/clerk" },
  { name: "Clay Labs", enabled: true, careers_url: "https://jobs.ashbyhq.com/claylabs" },
  { name: "Cohere", enabled: true, careers_url: "https://jobs.ashbyhq.com/cohere" },
  { name: "Coinbase", enabled: true, careers_url: "https://job-boards.greenhouse.io/coinbase" },
  { name: "Contentful", enabled: true, careers_url: "https://job-boards.greenhouse.io/contentful" },
  { name: "Cradle", enabled: true, careers_url: "https://jobs.ashbyhq.com/cradlebio" },
  { name: "Decagon", enabled: true, careers_url: "https://jobs.ashbyhq.com/decagon" },
  { name: "Deepgram", enabled: true, careers_url: "https://jobs.ashbyhq.com/deepgram" },
  { name: "DeepL", enabled: true, careers_url: "https://jobs.ashbyhq.com/DeepL" },
  { name: "Dropbox", enabled: true, careers_url: "https://job-boards.greenhouse.io/dropbox" },
  { name: "Duolingo", enabled: true, careers_url: "https://job-boards.greenhouse.io/duolingo" },
  { name: "ElevenLabs", enabled: true, careers_url: "https://jobs.ashbyhq.com/elevenlabs" },
  { name: "Faculty", enabled: true, careers_url: "https://jobs.ashbyhq.com/faculty" },
  { name: "Factorial", enabled: true, careers_url: "https://job-boards.greenhouse.io/factorial" },
  { name: "Figma", enabled: true, careers_url: "https://job-boards.greenhouse.io/figma" },
  { name: "Forto", enabled: true, careers_url: "https://jobs.lever.co/forto" },
  { name: "GetYourGuide", enabled: true, careers_url: "https://job-boards.greenhouse.io/getyourguide" },
  { name: "Glacis AI", enabled: true, careers_url: "https://jobs.ashbyhq.com/glacis-ai" },
  { name: "Glean", enabled: true, careers_url: "https://job-boards.greenhouse.io/gleanwork" },
  { name: "HelloFresh", enabled: true, careers_url: "https://job-boards.greenhouse.io/hellofresh" },
  { name: "Helsing", enabled: true, careers_url: "https://job-boards.greenhouse.io/helsing" },
  { name: "Hightouch", enabled: true, careers_url: "https://job-boards.greenhouse.io/hightouch" },
  { name: "Hootsuite", enabled: true, careers_url: "https://job-boards.greenhouse.io/hootsuite" },
  { name: "Hume", enabled: true, careers_url: "https://job-boards.greenhouse.io/humeai" },
  { name: "Inngest", enabled: true, careers_url: "https://jobs.ashbyhq.com/inngest" },
  { name: "Intercom", enabled: true, careers_url: "https://job-boards.greenhouse.io/intercom" },
  { name: "Isomorphic Labs", enabled: true, careers_url: "https://job-boards.greenhouse.io/isomorphiclabs" },
  { name: "Klue", enabled: true, careers_url: "https://jobs.ashbyhq.com/klue" },
  { name: "LangChain", enabled: true, careers_url: "https://jobs.ashbyhq.com/langchain" },
  { name: "Later", enabled: true, careers_url: "https://job-boards.greenhouse.io/later" },
  { name: "Lakera", enabled: true, careers_url: "https://jobs.ashbyhq.com/lakera.ai" },
  { name: "Legora", enabled: true, careers_url: "https://jobs.ashbyhq.com/legora" },
  { name: "Linear", enabled: true, careers_url: "https://jobs.ashbyhq.com/linear" },
  { name: "Lovable", enabled: true, careers_url: "https://jobs.ashbyhq.com/lovable" },
  { name: "Mercury", enabled: true, careers_url: "https://jobs.ashbyhq.com/mercury" },
  { name: "Mistral", enabled: true, careers_url: "https://jobs.lever.co/mistral" },
  { name: "N26", enabled: true, careers_url: "https://job-boards.greenhouse.io/n26" },
  { name: "n8n", enabled: true, careers_url: "https://jobs.ashbyhq.com/n8n" },
  { name: "Palantir", enabled: true, careers_url: "https://jobs.lever.co/palantir" },
  { name: "Parloa", enabled: true, careers_url: "https://job-boards.eu.greenhouse.io/parloa" },
  { name: "Perplexity", enabled: true, careers_url: "https://jobs.ashbyhq.com/perplexity" },
  { name: "Photoroom", enabled: true, careers_url: "https://jobs.ashbyhq.com/photoroom" },
  { name: "PhysicsX", enabled: true, careers_url: "https://job-boards.greenhouse.io/physicsx" },
  { name: "Pigment", enabled: true, careers_url: "https://jobs.lever.co/pigment" },
  { name: "Pinecone", enabled: true, careers_url: "https://jobs.ashbyhq.com/pinecone" },
  { name: "PlanetScale", enabled: true, careers_url: "https://job-boards.greenhouse.io/planetscale" },
  { name: "PolyAI", enabled: true, careers_url: "https://job-boards.eu.greenhouse.io/polyai" },
  { name: "Qonto", enabled: true, careers_url: "https://jobs.lever.co/qonto" },
  { name: "Replit", enabled: true, careers_url: "https://jobs.ashbyhq.com/replit" },
  { name: "Resend", enabled: true, careers_url: "https://jobs.ashbyhq.com/resend" },
  { name: "Robinhood", enabled: true, careers_url: "https://job-boards.greenhouse.io/robinhood" },
  { name: "Runpod", enabled: true, careers_url: "https://job-boards.greenhouse.io/runpod" },
  { name: "Runway", enabled: true, careers_url: "https://job-boards.greenhouse.io/runwayml" },
  { name: "Safari AI", enabled: true, careers_url: "https://job-boards.greenhouse.io/safariai" },
  { name: "Sanctuary AI", enabled: true, careers_url: "https://jobs.lever.co/sanctuary" },
  { name: "Scandit", enabled: true, careers_url: "https://job-boards.greenhouse.io/scandit" },
  { name: "Sierra", enabled: true, careers_url: "https://jobs.ashbyhq.com/sierra" },
  { name: "Speechmatics", enabled: true, careers_url: "https://job-boards.greenhouse.io/speechmatics" },
  { name: "Spotify", enabled: true, careers_url: "https://jobs.lever.co/spotify" },
  { name: "Stability AI", enabled: true, careers_url: "https://job-boards.greenhouse.io/stabilityai" },
  { name: "Stripe", enabled: true, careers_url: "https://job-boards.greenhouse.io/stripe" },
  { name: "SumUp", enabled: true, careers_url: "https://job-boards.greenhouse.io/sumup" },
  { name: "Supabase", enabled: true, careers_url: "https://jobs.ashbyhq.com/supabase" },
  { name: "Synthesia", enabled: true, careers_url: "https://jobs.ashbyhq.com/synthesia" },
  { name: "Temporal", enabled: true, careers_url: "https://job-boards.greenhouse.io/temporal" },
  { name: "Tinybird", enabled: true, careers_url: "https://jobs.ashbyhq.com/tinybird" },
  { name: "Trade Republic", enabled: true, careers_url: "https://job-boards.greenhouse.io/traderepublicbank" },
  { name: "Travelperk", enabled: true, careers_url: "https://jobs.ashbyhq.com/travelperk" },
  { name: "Vapi", enabled: true, careers_url: "https://jobs.ashbyhq.com/vapi" },
  { name: "Vercel", enabled: true, careers_url: "https://job-boards.greenhouse.io/vercel" },
  { name: "Vinted", enabled: true, careers_url: "https://jobs.lever.co/vinted" },
  { name: "W&B", enabled: true, careers_url: "https://jobs.lever.co/wandb" },
  { name: "Wayve", enabled: true, careers_url: "https://job-boards.greenhouse.io/wayve" },
  { name: "WorkOS", enabled: true, careers_url: "https://jobs.ashbyhq.com/workos" },
  { name: "Zapier", enabled: true, careers_url: "https://jobs.ashbyhq.com/zapier" },
];

export const DEFAULT_PORTAL_CATALOG_SIZE = DEFAULT_PORTAL_CATALOG.length;

export function defaultCatalogCopy(): PortalsTrackedCompany[] {
  return DEFAULT_PORTAL_CATALOG.map((c) => ({ ...c }));
}
